# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: rorski.com
show_downloads: false
theme: jekyll-theme-minimal
description: > # this means to ignore newlines until "baseurl:"
  Thoughts on clouds and other things
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://rorski.com"
github_username: rorski

# Build settings
markdown: kramdown
theme: jekyll-theme-minimal
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
